# Generated by Django 4.0.6 on 2022-07-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit_posts', '0002_commentlike_created_at_postlike_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='picture'),
        ),
    ]
